export const PRODUCT_LIST_REQUEST = "RODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "RODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "RODUCT_LIST_FAIL";

export const PRODUCT_DETAIlS_REQUEST = "RODUCT_DETAIlS_REQUEST";
export const PRODUCT_DETAIlS_SUCCESS = "RODUCT_DETAIlS_SUCCESS";
export const PRODUCT_DETAIlS_FAIL = "RODUCT_DETAIlS_FAIL";

export const PRODUCT_DELETE_REQUEST = "RODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "RODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "RODUCT_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "RODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "RODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "RODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "RODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "RODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "RODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "RODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "RODUCT_UPDATE_RESET";

