export const PRODUCT_LIST_REQUEST = "RODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "RODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "RODUCT_LIST_FAIL";

export const PRODUCT_DETAIlS_REQUEST = "RODUCT_DETAIlS_REQUEST";
export const PRODUCT_DETAIlS_SUCCESS = "RODUCT_DETAIlS_SUCCESS";
export const PRODUCT_DETAIlS_FAIL = "RODUCT_DETAIlS_FAIL";
